#!/usr/bin/env node
// Rebuild the fully offline renderer from package-lock.json-pinned packages.
// npm ci --ignore-scripts && npm run build:mermaid [-- --check]
import {build, version as esbuildVersion} from 'esbuild';
import {readFile, writeFile, readdir, access} from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath} from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const output = 'internal/admin/static/webui-mermaid-runtime.js';
const noticeOutput = 'internal/admin/static/webui-mermaid-LICENSE.txt';
const check = process.argv.includes('--check');
if (process.argv.slice(2).some(arg => arg !== '--check')) throw new Error('Usage: node scripts/build-mermaid.mjs [--check]');
const json = async file => JSON.parse(await readFile(path.join(root, file), 'utf8'));
const mermaidPackage = await json('node_modules/mermaid/package.json');
const packageConfig = await json('package.json');
if (packageConfig.devDependencies.mermaid !== mermaidPackage.version || packageConfig.devDependencies.esbuild !== esbuildVersion) throw new Error('Install the pinned dependencies with npm ci first.');
const result = await build({
  absWorkingDir: root,
  entryPoints: ['internal/admin/mermaid/renderer.js'],
  outfile: output,
  bundle: true,
  splitting: false,
  write: false,
  metafile: true,
  format: 'iife',
  platform: 'browser',
  target: ['es2020'],
  minify: true,
  charset: 'utf8',
  legalComments: 'external',
  banner: {js: `/*! Mermaid ${mermaidPackage.version}; esbuild ${esbuildVersion}. Generated by scripts/build-mermaid.mjs. Third-party notices: webui-mermaid-LICENSE.txt */`},
});
const generatedJS = result.outputFiles.find(file => file.path.endsWith('.js'));
const generatedLegal = result.outputFiles.find(file => file.path.endsWith('.LEGAL.txt'));
const outputMeta = result.metafile.outputs[output];
if (!generatedJS || !outputMeta || outputMeta.imports.length) throw new Error('The renderer must be a single self-contained classic script.');

const packages = new Map();
const prebundled = new Map();
for (const input of Object.keys(outputMeta.inputs).sort()) {
  if (!input.startsWith('node_modules/') || outputMeta.inputs[input].bytesInOutput === 0) continue;
  let directory = path.dirname(path.join(root, input));
  while (directory.startsWith(path.join(root, 'node_modules'))) {
    try {
      const metadata = JSON.parse(await readFile(path.join(directory, 'package.json'), 'utf8'));
      if (metadata.name && metadata.version) {
        packages.set(`${metadata.name}@${metadata.version}`, {metadata, directory});
        break;
      }
    } catch (error) {
      if (error.code !== 'ENOENT') throw error;
    }
    directory = path.dirname(directory);
  }
  // Mermaid publishes a few dependencies prebundled in its own chunks. Their
  // source maps retain the exact package/version; do not silently omit them.
  if (input.startsWith('node_modules/mermaid/')) {
    try {
      const map = await json(`${input}.map`);
      for (const source of map.sources ?? []) {
        const embedded = source.match(/\.pnpm\/([^/]+)\/node_modules\/((?:@[^/]+\/)?[^/]+)/);
        if (embedded) {
          const name = embedded[2];
          const version = embedded[1].slice(embedded[1].lastIndexOf('@') + 1).split('_')[0];
          prebundled.set(`${name}@${version}`, {name, version});
        }
      }
    } catch (error) {
      if (error.code !== 'ENOENT') throw error;
    }
  }
}

const notices = new Map();
for (const [id, {metadata, directory}] of packages) {
  const files = (await readdir(directory)).filter(name => /^(license|licence|copying|notice)([.-].*)?$/i.test(name)).sort();
  if (!files.length) throw new Error(`Missing license text for bundled package ${id}`);
  const sections = [];
  for (const file of files) {
    const text = (await readFile(path.join(directory, file), 'utf8')).trim();
    sections.push(`${file}\n\n${text}`);
  }
  notices.set(id, `${id}\nLicense: ${metadata.license ?? 'See license text'}\n\n${sections.join('\n\n')}`);
}
for (const [id, {name, version}] of prebundled) {
  if (notices.has(id)) continue;
  const licenseFile = `internal/admin/mermaid/licenses/${name.replaceAll('/', '-')}-${version}.txt`;
  await access(path.join(root, licenseFile));
  const text = (await readFile(path.join(root, licenseFile), 'utf8')).trim();
  notices.set(id, `${id}\nPrebundled by Mermaid; license copied from the published npm package.\n\n${text}`);
}
const divider = '\n\n' + '='.repeat(78) + '\n\n';
const noticesText = `Mermaid diagram renderer — third-party license notices\n\nGenerated by scripts/build-mermaid.mjs from the actual bundled inputs and\nMermaid's published source maps. Versions are pinned by package-lock.json.\n\n${[...notices.entries()].sort(([a], [b]) => a.localeCompare(b, 'en')).map(([, text]) => text).join(divider)}${generatedLegal ? `${divider}Additional license comments retained by esbuild\n\n${generatedLegal.text.trim()}` : ''}\n`;

for (const [file, contents] of [[output, generatedJS.contents], [noticeOutput, Buffer.from(noticesText)]]) {
  const destination = path.join(root, file);
  if (check) {
    const existing = await readFile(destination);
    if (!existing.equals(Buffer.from(contents))) throw new Error(`${file} is out of date. Run npm run build:mermaid.`);
  } else {
    await writeFile(destination, contents);
  }
}
console.log(`Mermaid ${mermaidPackage.version}: ${generatedJS.contents.byteLength.toLocaleString('en')} bytes, ${notices.size} package notices; ${check ? 'verified' : 'built'}.`);
